name: flutterhub
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  chopper: ^4.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  json_annotation: ^4.4.0
  nb_utils: ^4.4.14
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.1.8 # flutter pub run build_runner build --delete-conflicting-outputs
  chopper_generator: ^4.0.5
  flutter_gen: ^4.1.6
  flutter_launcher_icons: ^0.9.2 # flutter pub run flutter_launcher_icons:main
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.2 # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  mobx_codegen: null

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#131d25"
  image: assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#01579B"
  adaptive_icon_foreground: "assets/images/app_icon_adaptive.png"
