name: flutterhub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  chopper: ^4.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  json_annotation: ^4.4.0
  nb_utils: ^4.4.14
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.1.8
  chopper_generator: ^4.0.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  mobx_codegen:

flutter:
  generate: true
  uses-material-design: true
