name: flutterhub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chopper: ^4.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.8
  chopper_generator: ^4.0.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
